controller_list:
  - name: fake_cobot_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_arm_rotary
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses per group
  - group: cobot_arm
    pose: zero